import { IProduct } from "@/types";

export const DEMO_PRODUCTS: IProduct[] = [
  {
    _id: "1",
    name: "Luxury Combed Cotton Crew Socks",
    description: "Experience the pinnacle of comfort with our Luxury Crew Socks. Made from 100% premium combed cotton, these socks feature reinforced heel and toe for extra durability. The mid-calf length provides excellent coverage while the elastic arch support keeps them perfectly in place all day.",
    price: 299,
    mrp: 499,
    comparePrice: 499,
    discount: 40,
    category: "men",
    type: "crew",
    sockType: "crew",
    material: "cotton",
    occasion: ["office", "formal", "casual"],
    technologies: ["Silver Frost Anti-Odour", "Moisture Wicking", "Arch Support"],
    packOptions: [
      { label: "Single", size: 1, price: 299 },
      { label: "Pack of 3", size: 3, price: 749 },
      { label: "Pack of 5", size: 5, price: 1199 },
      { label: "Pack of 9", size: 9, price: 1999 },
    ],
    sizes: ["Free Size", "S (5-8)", "M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Midnight Black", hex: "#000000", imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop" },
      { name: "Navy Blue", hex: "#1a237e", imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop" },
      { name: "Charcoal", hex: "#424242", imageUrl: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop" },
      { name: "Classic White", hex: "#F5F5F5" },
    ],
    images: [
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
    ],
    stock: 150,
    sku: "RS-CRW-001",
    tags: ["premium", "crew", "cotton", "bestseller", "office"],
    isActive: true,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    rating: 4.8,
    reviewCount: 124,
    reviews: [
      { user: "Priya S.", rating: 5, comment: "Absolutely love these socks! The quality is top-notch and they feel amazing. Best crew socks I've ever owned.", date: new Date(Date.now() - 5 * 86400000).toISOString(), verified: true },
      { user: "Rahul M.", rating: 5, comment: "Finally found socks that last. The anti-odour technology really works. Wearing these daily to office.", date: new Date(Date.now() - 12 * 86400000).toISOString(), verified: true },
      { user: "Vikram R.", rating: 4, comment: "Good quality, comfortable fit. Wish they had more colour options.", date: new Date(Date.now() - 20 * 86400000).toISOString(), verified: false },
    ],
    materialCare: "Machine wash cold. Tumble dry low. Do not bleach. Do not iron directly on print.",
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Sports Performance Ankle Socks",
    description: "Engineered for peak performance, these sports ankle socks feature advanced moisture-wicking technology and strategic cushioning. Perfect for running, gym sessions, and high-intensity workouts. The reinforced toe and heel provide extra durability where you need it most.",
    price: 199,
    mrp: 349,
    comparePrice: 349,
    discount: 43,
    category: "men",
    type: "ankle",
    sockType: "ankle",
    material: "polyester",
    occasion: ["sports", "casual"],
    technologies: ["Moisture Wicking", "Cushioned Sole", "Arch Support", "Breathable Mesh"],
    packOptions: [
      { label: "Single", size: 1, price: 199 },
      { label: "Pack of 3", size: 3, price: 499 },
      { label: "Pack of 5", size: 5, price: 799 },
    ],
    sizes: ["Free Size", "M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Pure White", hex: "#FFFFFF", imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop" },
      { name: "Jet Black", hex: "#000000" },
      { name: "Sport Blue", hex: "#2196f3" },
    ],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
    ],
    stock: 200,
    sku: "RS-ANK-002",
    tags: ["sports", "performance", "ankle", "gym", "running"],
    isActive: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    rating: 4.5,
    reviewCount: 89,
    reviews: [
      { user: "Arjun D.", rating: 5, comment: "Perfect for my morning runs. Breathable and no blisters!", date: new Date(Date.now() - 8 * 86400000).toISOString(), verified: true },
      { user: "Sneha P.", rating: 4, comment: "Good cushioning. My husband loves them for the gym.", date: new Date(Date.now() - 15 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash cold with similar colors. Do not use fabric softener. Tumble dry low.",
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "Floral Bamboo Ankle Socks",
    description: "Elegant floral pattern ankle socks crafted from premium bamboo fibre. Naturally anti-bacterial, hypoallergenic, and incredibly soft. These eco-friendly socks are perfect for everyday wear and keep your feet fresh all day long.",
    price: 249,
    mrp: 399,
    comparePrice: 399,
    discount: 38,
    category: "women",
    type: "ankle",
    sockType: "ankle",
    material: "bamboo",
    occasion: ["casual", "office"],
    technologies: ["Zero Odour Bamboo", "Anti-Bacterial", "OEKO-TEX Certified", "Eco-Friendly"],
    packOptions: [
      { label: "Single", size: 1, price: 249 },
      { label: "Pack of 3", size: 3, price: 649 },
      { label: "Pack of 5", size: 5, price: 999 },
    ],
    sizes: ["Free Size", "S (5-8)", "M (6-9)", "L (7-10)"],
    colors: [
      { name: "Blush Pink", hex: "#e91e63", imageUrl: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop" },
      { name: "Soft White", hex: "#FAFAFA" },
      { name: "Lavender", hex: "#9C27B0" },
      { name: "Sage Green", hex: "#81C784" },
    ],
    images: [
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
    ],
    stock: 120,
    sku: "RS-WAN-003",
    tags: ["floral", "ankle", "bamboo", "women", "eco-friendly"],
    isActive: true,
    isFeatured: true,
    isNew: true,
    isTrending: false,
    rating: 4.9,
    reviewCount: 210,
    reviews: [
      { user: "Ananya K.", rating: 5, comment: "These are the softest socks I've ever worn. The bamboo material is amazing!", date: new Date(Date.now() - 3 * 86400000).toISOString(), verified: true },
      { user: "Meera J.", rating: 5, comment: "Beautiful design and so comfortable. Ordered 3 packs already!", date: new Date(Date.now() - 10 * 86400000).toISOString(), verified: true },
      { user: "Riya T.", rating: 4, comment: "Love the eco-friendly aspect. Great quality for the price.", date: new Date(Date.now() - 18 * 86400000).toISOString(), verified: false },
    ],
    materialCare: "Hand wash or machine wash on gentle cycle. Air dry recommended. Do not bleach.",
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "Kids Rainbow Fun Crew Socks",
    description: "Fun and colourful rainbow crew socks that kids will love! Made from soft combed cotton with just the right amount of stretch. Features non-slip grip dots on the sole for safety. Perfect for school, play dates, and everyday adventures.",
    price: 149,
    mrp: 249,
    comparePrice: 249,
    discount: 40,
    category: "kids",
    type: "crew",
    sockType: "crew",
    material: "cotton",
    occasion: ["casual"],
    technologies: ["Non-Slip Grip", "Soft Combed Cotton"],
    packOptions: [
      { label: "Single", size: 1, price: 149 },
      { label: "Pack of 3", size: 3, price: 399 },
      { label: "Pack of 5", size: 5, price: 599 },
      { label: "Pack of 9", size: 9, price: 999 },
    ],
    sizes: ["XS (1-3)", "S (4-6)", "M (7-9)"],
    colors: [
      { name: "Rainbow", hex: "#FF9800", imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop" },
      { name: "Blue Stripes", hex: "#42A5F5" },
      { name: "Pink Stars", hex: "#EC407A" },
    ],
    images: [
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop",
    ],
    stock: 180,
    sku: "RS-KCR-004",
    tags: ["kids", "rainbow", "colorful", "fun", "school"],
    isActive: true,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    rating: 4.7,
    reviewCount: 56,
    reviews: [
      { user: "Sneha P.", rating: 5, comment: "My kids absolutely adore these! The grip dots are a great safety feature.", date: new Date(Date.now() - 7 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash warm. Tumble dry medium. Do not bleach.",
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    name: "Formal Merino Wool Dress Socks",
    description: "Elevate your formal wear with these exquisite merino wool dress socks. Ultra-fine 18.5 micron merino regulates temperature year-round, keeping your feet warm in winter and cool in summer. The ribbed calf design ensures they stay up all day.",
    price: 449,
    mrp: 699,
    comparePrice: 699,
    discount: 36,
    category: "men",
    type: "crew",
    sockType: "over-the-calf",
    material: "merino",
    occasion: ["formal", "office"],
    technologies: ["Temperature Regulating", "Odour Resistant", "OEKO-TEX Certified"],
    packOptions: [
      { label: "Single", size: 1, price: 449 },
      { label: "Pack of 3", size: 3, price: 1099 },
      { label: "Pack of 5", size: 5, price: 1749 },
    ],
    sizes: ["M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Classic Black", hex: "#000000", imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop" },
      { name: "Oxford Grey", hex: "#616161" },
      { name: "Burgundy", hex: "#880E4F" },
      { name: "Navy", hex: "#1a237e" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    ],
    stock: 60,
    sku: "RS-FDR-005",
    tags: ["formal", "dress", "elegant", "merino", "wool", "premium"],
    isActive: true,
    isFeatured: true,
    isNew: false,
    isTrending: false,
    rating: 4.6,
    reviewCount: 78,
    reviews: [
      { user: "Vikram R.", rating: 5, comment: "Best dress socks I've owned. Perfect for business meetings.", date: new Date(Date.now() - 6 * 86400000).toISOString(), verified: true },
      { user: "Suresh K.", rating: 4, comment: "Excellent quality merino wool. Comfortable all day at the office.", date: new Date(Date.now() - 14 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Hand wash recommended. Lay flat to dry. Do not tumble dry. Do not bleach.",
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    name: "Modal Lounge No-Show Socks",
    description: "Ultra-thin no-show socks made from premium modal fabric. Features a silicone grip at the heel to prevent slipping. Perfect with loafers, sneakers, and boat shoes. The seamless toe construction eliminates irritation for all-day comfort.",
    price: 179,
    mrp: 299,
    comparePrice: 299,
    discount: 40,
    category: "unisex",
    type: "ankle",
    sockType: "no-show",
    material: "modal",
    occasion: ["casual", "travel"],
    technologies: ["Zero Odour Modal", "Silicone Heel Grip", "Seamless Toe"],
    packOptions: [
      { label: "Single", size: 1, price: 179 },
      { label: "Pack of 3", size: 3, price: 449 },
      { label: "Pack of 5", size: 5, price: 699 },
    ],
    sizes: ["Free Size", "S (5-8)", "M (6-9)", "L (7-10)"],
    colors: [
      { name: "Nude Beige", hex: "#D7CCC8", imageUrl: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop" },
      { name: "Black", hex: "#212121" },
      { name: "Grey", hex: "#9E9E9E" },
    ],
    images: [
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop",
    ],
    stock: 95,
    sku: "RS-UNS-006",
    tags: ["no-show", "invisible", "modal", "loafer", "unisex"],
    isActive: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    rating: 4.4,
    reviewCount: 43,
    reviews: [
      { user: "Arjun D.", rating: 4, comment: "Great no-show socks. The silicone grip works well.", date: new Date(Date.now() - 9 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash cold on gentle cycle. Air dry. Do not bleach or iron.",
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "7",
    name: "Cashmere Blend Winter Socks",
    description: "Indulge in pure luxury with our cashmere blend winter socks. A sumptuous mix of cashmere and merino wool creates the ultimate warmth and softness. Ribbed construction ensures a snug fit, while the extra-thick cushioned sole provides plush comfort.",
    price: 599,
    mrp: 999,
    comparePrice: 999,
    discount: 40,
    category: "women",
    type: "crew",
    sockType: "crew",
    material: "cashmere",
    occasion: ["casual", "festive"],
    technologies: ["Temperature Regulating", "Extra Cushioned", "Luxury Cashmere"],
    packOptions: [
      { label: "Single", size: 1, price: 599 },
      { label: "Pack of 3", size: 3, price: 1499 },
    ],
    sizes: ["Free Size", "S (5-8)", "M (6-9)"],
    colors: [
      { name: "Heather Grey", hex: "#BDBDBD", imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop" },
      { name: "Cream", hex: "#FFF8E1" },
      { name: "Dusty Rose", hex: "#CE93D8" },
      { name: "Forest Green", hex: "#2E7D32" },
    ],
    images: [
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
    ],
    stock: 40,
    sku: "RS-WCS-007",
    tags: ["cashmere", "winter", "luxury", "warm", "women", "gift"],
    isActive: true,
    isFeatured: true,
    isNew: false,
    isTrending: false,
    rating: 4.9,
    reviewCount: 35,
    reviews: [
      { user: "Meera J.", rating: 5, comment: "These are heavenly! So soft and warm. Perfect for winter evenings.", date: new Date(Date.now() - 4 * 86400000).toISOString(), verified: true },
      { user: "Ananya K.", rating: 5, comment: "Gifted these to my mom and she loves them. Premium quality!", date: new Date(Date.now() - 11 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Hand wash only in cold water. Do not wring. Lay flat to dry. Store folded.",
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "8",
    name: "Quarter Length Gym Socks",
    description: "Designed for intense training sessions, these quarter-length gym socks provide the perfect balance of coverage and ventilation. Features targeted compression zones, mesh ventilation panels, and deep-heel pocket for a secure fit during any workout.",
    price: 229,
    mrp: 399,
    comparePrice: 399,
    discount: 43,
    category: "unisex",
    type: "ankle",
    sockType: "quarter",
    material: "polyester",
    occasion: ["sports"],
    technologies: ["Compression Zones", "Mesh Ventilation", "Deep Heel Pocket", "Moisture Wicking"],
    packOptions: [
      { label: "Single", size: 1, price: 229 },
      { label: "Pack of 3", size: 3, price: 579 },
      { label: "Pack of 5", size: 5, price: 899 },
    ],
    sizes: ["M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Neon Green", hex: "#76FF03", imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop" },
      { name: "Black", hex: "#212121" },
      { name: "Electric Blue", hex: "#2979FF" },
    ],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
    ],
    stock: 130,
    sku: "RS-UQR-008",
    tags: ["gym", "quarter", "sports", "training", "compression"],
    isActive: true,
    isFeatured: false,
    isNew: true,
    isTrending: false,
    rating: 4.3,
    reviewCount: 29,
    reviews: [
      { user: "Rahul M.", rating: 4, comment: "Great grip and support for weight training. Good value for the price.", date: new Date(Date.now() - 13 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash cold. Do not use fabric softener. Tumble dry low.",
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "9",
    name: "Silk Blend Festive Socks",
    description: "Celebrate in style with our silk-blend festive socks. A luxurious mix of silk and cotton with intricate ethnic patterns inspired by Indian textile traditions. Perfect for weddings, Diwali celebrations, and special occasions.",
    price: 399,
    mrp: 649,
    comparePrice: 649,
    discount: 39,
    category: "men",
    type: "crew",
    sockType: "crew",
    material: "silk-blend",
    occasion: ["festive", "formal"],
    technologies: ["Silk Blend Comfort", "Hand-Finished Details"],
    packOptions: [
      { label: "Single", size: 1, price: 399 },
      { label: "Pack of 3", size: 3, price: 999 },
    ],
    sizes: ["Free Size", "M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Royal Maroon", hex: "#800020", imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop" },
      { name: "Gold Beige", hex: "#C9A96E" },
      { name: "Deep Teal", hex: "#00695C" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
    ],
    stock: 45,
    sku: "RS-MFS-009",
    tags: ["festive", "silk", "wedding", "diwali", "gift", "premium"],
    isActive: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    rating: 4.7,
    reviewCount: 18,
    reviews: [
      { user: "Suresh K.", rating: 5, comment: "Wore these to a wedding and got so many compliments! Gorgeous design.", date: new Date(Date.now() - 2 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Hand wash only in lukewarm water. Do not wring. Air dry. Do not bleach or iron.",
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "10",
    name: "Cotton Stripe Casual Socks",
    description: "Classic stripe pattern casual socks that pair perfectly with jeans and sneakers. Made from breathable combed cotton with spandex for a comfortable stretch fit. A wardrobe essential for effortless everyday style.",
    price: 179,
    mrp: 299,
    comparePrice: 299,
    discount: 40,
    category: "women",
    type: "crew",
    sockType: "crew",
    material: "cotton",
    occasion: ["casual", "travel"],
    technologies: ["Combed Cotton", "Spandex Stretch"],
    packOptions: [
      { label: "Single", size: 1, price: 179 },
      { label: "Pack of 3", size: 3, price: 449 },
      { label: "Pack of 5", size: 5, price: 699 },
    ],
    sizes: ["Free Size", "S (5-8)", "M (6-9)"],
    colors: [
      { name: "Multicolour", hex: "#9C27B0", imageUrl: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop" },
      { name: "Pastel Blue", hex: "#90CAF9" },
      { name: "Coral", hex: "#FF7043" },
    ],
    images: [
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&h=600&fit=crop",
    ],
    stock: 110,
    sku: "RS-WCS-010",
    tags: ["casual", "stripe", "women", "everyday"],
    isActive: true,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    rating: 4.4,
    reviewCount: 67,
    reviews: [
      { user: "Riya T.", rating: 4, comment: "Nice stripes, comfortable cotton. Good for daily wear.", date: new Date(Date.now() - 16 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash cold with similar colours. Tumble dry low.",
    createdAt: new Date(Date.now() - 75 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "11",
    name: "Bamboo Travel Compression Socks",
    description: "Stay comfortable on long flights and road trips with these bamboo travel compression socks. Graduated compression improves circulation and reduces swelling. The natural bamboo fibre keeps feet cool, dry, and odour-free even after hours of travel.",
    price: 349,
    mrp: 549,
    comparePrice: 549,
    discount: 36,
    category: "unisex",
    type: "crew",
    sockType: "knee-high",
    material: "bamboo",
    occasion: ["travel", "office"],
    technologies: ["Graduated Compression", "Anti-Odour Bamboo", "Circulation Support", "OEKO-TEX Certified"],
    packOptions: [
      { label: "Single", size: 1, price: 349 },
      { label: "Pack of 3", size: 3, price: 899 },
    ],
    sizes: ["S (5-8)", "M (6-9)", "L (7-10)", "XL (8-11)"],
    colors: [
      { name: "Black", hex: "#212121", imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop" },
      { name: "Navy", hex: "#1a237e" },
      { name: "Tan", hex: "#D7CCC8" },
    ],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    ],
    stock: 55,
    sku: "RS-UKH-011",
    tags: ["travel", "compression", "bamboo", "knee-high", "flight"],
    isActive: true,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    rating: 4.5,
    reviewCount: 22,
    reviews: [
      { user: "Priya S.", rating: 5, comment: "Wore these on a 12-hour flight and my legs felt so much better!", date: new Date(Date.now() - 21 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Machine wash cold on gentle cycle. Air dry. Do not bleach.",
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "12",
    name: "Luxury Gift Box — Pack of 5",
    description: "The perfect gift for someone who appreciates quality. This curated gift box includes 5 pairs of our finest socks — a mix of crew, ankle, and no-show styles in complementary colours. Presented in an elegant matte-black gift box with gold foil branding.",
    price: 1499,
    mrp: 2495,
    comparePrice: 2495,
    discount: 40,
    category: "unisex",
    type: "crew",
    sockType: "crew",
    material: "cotton",
    occasion: ["festive", "casual", "formal"],
    technologies: ["Silver Frost Anti-Odour", "Combed Cotton", "OEKO-TEX Certified"],
    packOptions: [
      { label: "Gift Box of 5", size: 5, price: 1499 },
      { label: "Gift Box of 9", size: 9, price: 2499 },
    ],
    sizes: ["Free Size", "M (6-9)", "L (7-10)"],
    colors: [
      { name: "Assorted", hex: "#A8874A", imageUrl: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop" },
    ],
    images: [
      "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop",
    ],
    stock: 30,
    sku: "RS-GBX-012",
    tags: ["gift", "giftbox", "premium", "bundle", "festive", "wedding"],
    isActive: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    rating: 4.8,
    reviewCount: 42,
    reviews: [
      { user: "Ananya K.", rating: 5, comment: "Gifted this to my brother for his birthday. He loved the packaging!", date: new Date(Date.now() - 1 * 86400000).toISOString(), verified: true },
      { user: "Arjun D.", rating: 5, comment: "Best gift option for sock lovers. Beautiful presentation.", date: new Date(Date.now() - 8 * 86400000).toISOString(), verified: true },
    ],
    materialCare: "Individual care instructions included with each pair in the box.",
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Helper to get product by ID
export function getProductById(id: string): IProduct | undefined {
  return DEMO_PRODUCTS.find((p) => p._id === id);
}

// Helper to get products by filter
export function getFilteredProducts(filters: {
  category?: string;
  sockType?: string;
  material?: string;
  occasion?: string;
  isFeatured?: boolean;
  isNew?: boolean;
  isTrending?: boolean;
  search?: string;
}): IProduct[] {
  return DEMO_PRODUCTS.filter((p) => {
    if (!p.isActive) return false;
    if (filters.category && filters.category !== "all" && p.category !== filters.category) return false;
    if (filters.sockType && p.sockType !== filters.sockType) return false;
    if (filters.material && p.material !== filters.material) return false;
    if (filters.occasion && !p.occasion.includes(filters.occasion as typeof p.occasion[number])) return false;
    if (filters.isFeatured && !p.isFeatured) return false;
    if (filters.isNew && !p.isNew) return false;
    if (filters.isTrending && !p.isTrending) return false;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      if (
        !p.name.toLowerCase().includes(q) &&
        !p.tags.some((t) => t.toLowerCase().includes(q)) &&
        !p.description.toLowerCase().includes(q)
      ) return false;
    }
    return true;
  });
}

// Helper to get related products
export function getRelatedProducts(product: IProduct, limit = 4): IProduct[] {
  return DEMO_PRODUCTS
    .filter((p) => p._id !== product._id && p.isActive && (p.category === product.category || p.sockType === product.sockType))
    .slice(0, limit);
}
